import PptxGenJS from 'pptxgenjs';

// ============================================================
// TEMPLATE THEMES
// ============================================================

const THEMES = {
  'modern-professional': {
    bg: 'F8FAFC',
    titleBg: '4F46E5',
    primary: '4F46E5',
    secondary: '818CF8',
    text: '1E293B',
    lightText: 'FFFFFF',
    accent: 'C7D2FE',
    fontFace: 'Calibri',
  },
  'academic-classic': {
    bg: 'FFFFFF',
    titleBg: '0F172A',
    primary: '0F172A',
    secondary: '475569',
    text: '0F172A',
    lightText: 'FFFFFF',
    accent: '94A3B8',
    fontFace: 'Georgia',
  },
  'creative-vibrant': {
    bg: 'FDF2F8',
    titleBg: 'EC4899',
    primary: 'EC4899',
    secondary: 'F472B6',
    text: '1E293B',
    lightText: 'FFFFFF',
    accent: 'FBCFE8',
    fontFace: 'Calibri',
  },
  'minimal-elegant': {
    bg: 'F0FDF4',
    titleBg: '059669',
    primary: '059669',
    secondary: '34D399',
    text: '1E293B',
    lightText: 'FFFFFF',
    accent: 'A7F3D0',
    fontFace: 'Calibri',
  },
};

// ============================================================
// PPTX GENERATION
// ============================================================

export function generatePptx(slides, { title, template = 'modern-professional' }) {
  const theme = THEMES[template] || THEMES['modern-professional'];
  const pptx = new PptxGenJS();

  pptx.author = 'EduSlide AI';
  pptx.company = 'EduSlide AI';
  pptx.subject = title;
  pptx.title = title;
  pptx.layout = 'LAYOUT_WIDE'; // 13.33 x 7.5 inches

  slides.forEach((slide, index) => {
    const pptSlide = pptx.addSlide();

    if (slide.layout === 'title' || index === 0) {
      renderTitleSlide(pptSlide, slide, theme);
    } else if (slide.layout === 'summary' || index === slides.length - 1) {
      renderSummarySlide(pptSlide, slide, theme);
    } else if (slide.layout === 'two-column') {
      renderTwoColumnSlide(pptSlide, slide, theme, index);
    } else {
      renderContentSlide(pptSlide, slide, theme, index);
    }

    // Add slide number (bottom-right)
    if (index > 0) {
      pptSlide.addText(`${index + 1}`, {
        x: 12.0, y: 6.9, w: 1.0, h: 0.4,
        fontSize: 10,
        color: theme.secondary,
        fontFace: theme.fontFace,
        align: 'right',
      });
    }

    // Speaker notes
    if (slide.notes) {
      pptSlide.addNotes(slide.notes);
    }
  });

  return pptx;
}

// ============================================================
// SLIDE RENDERERS
// ============================================================

function renderTitleSlide(pptSlide, slide, theme) {
  // Full-color background
  pptSlide.background = { fill: theme.titleBg };

  // Decorative accent bar
  pptSlide.addShape('rect', {
    x: 0, y: 5.2, w: 13.33, h: 0.08, fill: { color: theme.secondary },
  });

  // Title
  pptSlide.addText(slide.title, {
    x: 1.0, y: 1.8, w: 11.33, h: 1.5,
    fontSize: 40,
    fontFace: theme.fontFace,
    color: theme.lightText,
    bold: true,
    align: 'center',
    lineSpacing: 48,
  });

  // Subtitle
  if (slide.subtitle) {
    pptSlide.addText(slide.subtitle, {
      x: 2.0, y: 3.5, w: 9.33, h: 0.8,
      fontSize: 20,
      fontFace: theme.fontFace,
      color: theme.accent,
      align: 'center',
    });
  }

  // Branding
  pptSlide.addText('Generated by EduSlide AI', {
    x: 1.0, y: 6.2, w: 11.33, h: 0.5,
    fontSize: 12,
    fontFace: theme.fontFace,
    color: theme.accent,
    align: 'center',
    italic: true,
  });
}

function renderContentSlide(pptSlide, slide, theme, index) {
  pptSlide.background = { fill: theme.bg };

  // Left accent bar
  pptSlide.addShape('rect', {
    x: 0, y: 0, w: 0.15, h: 7.5, fill: { color: theme.primary },
  });

  // Top stripe
  pptSlide.addShape('rect', {
    x: 0, y: 0, w: 13.33, h: 0.06, fill: { color: theme.secondary },
  });

  // Title
  pptSlide.addText(slide.title, {
    x: 0.8, y: 0.4, w: 11.5, h: 0.9,
    fontSize: 28,
    fontFace: theme.fontFace,
    color: theme.primary,
    bold: true,
  });

  // Divider line
  pptSlide.addShape('rect', {
    x: 0.8, y: 1.35, w: 2.5, h: 0.04, fill: { color: theme.secondary },
  });

  // Bullet items
  const bullets = (slide.content || []).map((text) => ({
    text,
    options: {
      fontSize: 18,
      fontFace: theme.fontFace,
      color: theme.text,
      bullet: { type: 'number', numberType: 'arabicPeriod' },
      lineSpacing: 32,
      paraSpaceBefore: 6,
    },
  }));

  pptSlide.addText(bullets, {
    x: 1.0, y: 1.7, w: 11.0, h: 5.0,
    valign: 'top',
  });
}

function renderTwoColumnSlide(pptSlide, slide, theme, index) {
  pptSlide.background = { fill: theme.bg };

  // Top accent bar
  pptSlide.addShape('rect', {
    x: 0, y: 0, w: 13.33, h: 0.06, fill: { color: theme.primary },
  });

  // Title
  pptSlide.addText(slide.title, {
    x: 0.8, y: 0.4, w: 11.5, h: 0.9,
    fontSize: 28,
    fontFace: theme.fontFace,
    color: theme.primary,
    bold: true,
  });

  // Divider line under title
  pptSlide.addShape('rect', {
    x: 0.8, y: 1.35, w: 2.5, h: 0.04, fill: { color: theme.secondary },
  });

  const items = slide.content || [];
  const mid = Math.ceil(items.length / 2);
  const leftItems = items.slice(0, mid);
  const rightItems = items.slice(mid);

  // Left column
  const leftBullets = leftItems.map((text) => ({
    text,
    options: {
      fontSize: 16,
      fontFace: theme.fontFace,
      color: theme.text,
      bullet: true,
      lineSpacing: 28,
      paraSpaceBefore: 6,
    },
  }));

  pptSlide.addText(leftBullets, {
    x: 0.8, y: 1.7, w: 5.5, h: 5.0,
    valign: 'top',
  });

  // Vertical divider
  pptSlide.addShape('rect', {
    x: 6.55, y: 1.7, w: 0.03, h: 4.5, fill: { color: theme.accent },
  });

  // Right column
  const rightBullets = rightItems.map((text) => ({
    text,
    options: {
      fontSize: 16,
      fontFace: theme.fontFace,
      color: theme.text,
      bullet: true,
      lineSpacing: 28,
      paraSpaceBefore: 6,
    },
  }));

  pptSlide.addText(rightBullets, {
    x: 7.0, y: 1.7, w: 5.5, h: 5.0,
    valign: 'top',
  });
}

function renderSummarySlide(pptSlide, slide, theme) {
  // Summary uses title-style background
  pptSlide.background = { fill: theme.titleBg };

  // Title
  pptSlide.addText(slide.title, {
    x: 1.0, y: 0.8, w: 11.33, h: 1.0,
    fontSize: 32,
    fontFace: theme.fontFace,
    color: theme.lightText,
    bold: true,
    align: 'center',
  });

  // Divider
  pptSlide.addShape('rect', {
    x: 5.0, y: 2.0, w: 3.33, h: 0.04, fill: { color: theme.secondary },
  });

  // Bullet points
  const bullets = (slide.content || []).map((text) => ({
    text,
    options: {
      fontSize: 18,
      fontFace: theme.fontFace,
      color: theme.accent,
      bullet: { code: '2713' }, // ✓ checkmark
      lineSpacing: 32,
      paraSpaceBefore: 8,
    },
  }));

  pptSlide.addText(bullets, {
    x: 2.0, y: 2.5, w: 9.33, h: 4.0,
    valign: 'top',
  });

  // Footer
  pptSlide.addText('Thank you! | EduSlide AI', {
    x: 1.0, y: 6.2, w: 11.33, h: 0.5,
    fontSize: 14,
    fontFace: theme.fontFace,
    color: theme.accent,
    align: 'center',
    italic: true,
  });
}

// ============================================================
// DOWNLOAD HELPER
// ============================================================

export async function downloadPptx(slides, { title, template }) {
  const pptx = generatePptx(slides, { title, template });
  const fileName = `${title.replace(/[^a-zA-Z0-9 ]/g, '').trim().replace(/\s+/g, '_')}_EduSlide.pptx`;
  await pptx.writeFile({ fileName });
  return fileName;
}
